version: '3'
services:
  app:
    build: 
      context: .
    command: bundle exec puma -C config/puma.rb

    volumes:
      - .:/daijobso
      - public-data:/daijobso/public
      - tmp-data:/daijobso/tmp
      - log-data:/daijobso/log
    networks:
      - daijobso-network
    depends_on: 
      - db
    
  db:
    image: mysql:8.0.29
    environment: 
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PSSSWORD: password
      MYSQL_DATABASE: daijobso_development
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - daijobso-network

  web:
    build:
      context: ./nginx_docker
    volumes:
      - public-data:/daijobso/public
      - tmp-data:/daijobso/tmp
    ports:
      - 80:80
    depends_on:
      - app

volumes: 
  public-data:
  tmp-data:
  log-data:
  db-data:

networks: 
  daijobso-network:
    external: true